import Head from 'next/head'
import Hero from '../components/Hero'
import Section from '../layouts/section';
import ContentBlock from '../components/ContentBlock';
import Img from 'react-optimized-image';
import daveImage from "../public/david-hero2.jpeg";

export async function getStaticProps() {
  return {
    props: {
      title: "David Who?",
      content: "I'm some content"
    }
  }
}

export default function Home(props) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Section>
        <ContentBlock {...props}>
          <Img 
            src={daveImage} 
            webp 
            sizes={[400, 800]} 
            breakpoints={[600, 1000]}
            loading="lazy"
            style={{objectFit: "cover", objectPosition: "center"}}/>
        </ContentBlock>
      </Section>
    </div>
  )
}
